//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapStone6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int taskID { get; set; }
        public string task1 { get; set; }
        public string dateAssigned { get; set; }
        public string dateDue { get; set; }
        public bool complete { get; set; }
    }
}
